### ISSUE TITLE
1.10 to 1.11: $chatcallUserId

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1554]
When upgrading from 1.10.x to 1.11.x, I get this error:

Fatal error:  Uncaught exception 'ReflectionException' with message 'Property Chamilo\UserBundle\Entity\User::$chatcallUserId does not exist' in /var/www/chamilo.beeznest.com/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
Stack trace:
#0 /var/www/chamilo.beeznest.com/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(80): ReflectionProperty->__construct('Chamilo\\UserBun...', 'chatcallUserId')
#1 /var/www/chamilo.beeznest.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(893): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('Chamilo\\UserBun...', 'chatcallUserId')
#2 /var/www/chamilo.beeznest.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(540): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService))
#3 /var/www/chamilo.beeznest.com/www/vendor/doctrine/common/lib/Doctr in /var/www/chamilo.beeznest.com/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 80

There's probably a possibility to add an additional check to the upgrade procedure...

**Comment by ywarnier** [comment]
This doesn't fix the issue. I think the problem is more complex.
Apparently, it happens *after* the database migration of 1.10 to 1.11, so the full process of 1.9 to 1.10 seems to be fine.
Maybe something of the 1.9 or 1.10 entities is still "loaded" when we reach the end of the migration from 1.10 to 1.11?

**Comment by ywarnier** [comment]
In 1.9.x, there is no existence of any chatcallUserId term. In 1.11.x either. However, there is in 1.10.x (in src/Chamilo/UserBundle/Entity/User.php), and it seems like the entity is getting cached in app/cache/__CG__ChamiloUserBundleEntityUser.php. Maybe if we cleared the cache between the 1.9 to 1.10 and the 1.10 to 1.11 upgrades, we wouldn't have the issue...

**Comment by ywarnier** [comment]
This was due to Doctrine cache saving this whomever-knows-where (not in the Chamilo cache directory) from version 1.10.
I fixed it launching (on the command line):
php bin/doctrine.php orm:clear-cache:result
