### ISSUE TITLE
Time out bug

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#1765]
### Current behavior / Resultado actual / Résultat actuel
If a student leaves a course open on a Learning Path page, when the page times out the login box is shown WITHIN the Learning Path.  This results in the homepage or course appearing as though it were a Learning Path page.
![time out in course1](https://cloud.githubusercontent.com/assets/21216499/24081077/92f0e526-0ca3-11e7-8a57-d4a429461e46.jpg)
![login again](https://cloud.githubusercontent.com/assets/21216499/24081080/9ba90ce8-0ca3-11e7-977a-393391d8cb2a.jpg)

### Expected behavior / Resultado esperado / Résultat attendu
When time out is reached the login page should appear on top and not within the Learning Path

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. nter any course and leave page unattended until time out.
2. Login or return to homepage using the info displayed WITHIN the Learning Path.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by ywarnier** [comment]
Good suggestion. Won't be able to include it in 1.11.4 though, so setting to 2.0.

**Comment by christianbeeznest** [comment]
This issue has been resolved in version 2.0, where the login page now correctly appears on top after a session timeout, instead of within the Learning Path.

**Comment by ywarnier** [comment]
@christianbeeznest When I am in a learning path and my session expires and I move to the next element, I should be redirected entirely to the login page. Currently, the login box opens in the content iframe.

![Image](https://github.com/user-attachments/assets/7d4132b5-3692-4049-8e35-125665d02195)

If I then sign in (currently), I get double menus.

![Image](https://github.com/user-attachments/assets/2fdb8b50-59e1-4ada-9abb-2816073c4bfb)

**Comment by ywarnier** [comment]
The previous comment was made on an outdated version of the code.

@christianbeeznest 
When I am in a learning path and I delete my cookies then I click another item in the table of contents, Chamilo takes a long time then shows me the login box in the content frame and when I try to click on it, it disappears, leaving me with a content frame with the title of the step and the rest is blank.

When I click on any link/menu, if I'm not logged in and the course is not public, I should see the login page only (full page). Not a login page inserted in the content frame.

**Comment by christianbeeznest** [comment]
It is fixed and improved with the PR https://github.com/christianbeeznest/chamilo-lms/commit/875ae7a8ec148459ceae7a88dc9a048ad5a75c2b 

Detects when the login page is loaded inside the iframe and redirects the user to the full login page. Also shows a temporary overlay to prevent flashing the login form before redirecting.

**Comment by ywarnier** [comment]
@christianbeeznest With this change, when my portal is in production mode and I delete the chamilo2 cookie while inside a learning path, I get an HTTP 500 error in the browser and my error_log says:
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Chamilo\\CoreBundle\\Exception\\NotAllowedException: You're not allowed in this course in /var/www/test/www/src/CoreBundle/EventListener/CidReqListener.php:119
Stack trace:
#0 /var/www/test/www/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Chamilo\\CoreBundle\\EventListener\\CidReqListener->onKernelRequest()
#1 /var/www/test/www/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#2 /var/www/test/www/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#3 /var/www/test/www/vendor/symfony/http-kernel/HttpKernel.php(157): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#4 /var/www/testing26.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel...', referer: https://test/main/lp/lp_controller.php?cid=4&sid=0&gid=0&gradebook=0&origin=&action=view&lp_id=1
```

This seems like an issue with managing exceptions while in prod mode...

**Comment by ywarnier** [comment]
In dev mode, I get redirected correctly (although the login form appears for a few second in the iframe before the redirection).

**Comment by christianbeeznest** [comment]
Hi @ywarnier ,

It is checked last feedbacks with this PR https://github.com/chamilo/chamilo-lms/pull/6305

Thanks for confirmation.

**Comment by ywarnier** [comment]
Now tested and approved.
