### ISSUE TITLE
Fatal error in php when migrating to 1.11.2: unknow column 't0.email_canonical' in 'field list'

### ISSUE THREAD

**Issue by dauzeine** [chamilo/chamilo-lms#2136]
Hi,
I think I succeed to upgrade from 1.9 to 1.10.4 and then to 1.11.2 except for one thing. In my 1.11.2, when I want to access any course, I have a blank page. The php error is:

PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '*t0.email_canonical*' in '*field list*'' in /var/www/html/chamilo_good/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/html/chamilo_good/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)\n#1 /var/www/html/chamilo_good/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /var/www/html/chamilo_good/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(748): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.id AS...', Array, Array)\n#3 /var/www/html/chamilo_good/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(411): Doctrine\\ORM\\Persisters\\BasicEntityPersister->load(Array)\n#4 /var/www/html/chamilo_good/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(154): Doctrine\\ORM\\EntityManager->find('Chamilo\\\\UserBun...', 218, 0, NULL)\n#5 /var/www/html in /var/www/html/chamilo_good/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71
It seems that a colum hadn't been created...

David

**Comment by dauzeine** [comment]
The same as https://github.com/chamilo/chamilo-lms/issues/1958
