### ISSUE TITLE
impossibilité d'importé un exercice qti2 dans chamilo 1.11.6.alpha1

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2277]
### Current behavior / Resultado actual / Résultat actuel
l'exercice est importé mais il est vide
### Expected behavior / Resultado esperado / Résultat attendu
exercice importé
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
dans un cours aller dans exercices et importer  exercices QTI2
### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.6.alpha1

**Comment by jmontoyaa** [comment]
Est-ce que vous pouvez montrer un exemple ici?

https://11.chamilo.org/ (admin/admin)

**Comment by alexiye** [comment]
Création d'un cours puis essai d'importation et affichage suivant :
Notice: Undefined property: stdClass::$save_correct_answers in /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php on line 1803

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'save_correct_answers' cannot be null in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(Array) #1 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/11.chamilo.org/www/main/inc/lib/database.lib.php(450): Doctrine\DBAL\Statement->execute(Array) #3 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(1824): Database::insert('c_quiz', Array) #4 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(188): Chamilo\CourseBundle\Component\CourseCopy\CourseRestorer->restore_quizzes(0, false, '') #5 /var/www/11.chamilo.org/www/main/coursecopy/import_backup.php(101): Chamilo\CourseBun in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 118

**Comment by alexiye** [comment]
https://11.chamilo.org/main/exercise/admin.php?cidReq=IMPORTEXERCICEQTI2&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=746

**Comment by alexiye** [comment]
[qti2_export_1.zip](https://github.com/chamilo/chamilo-lms/files/1602804/qti2_export_1.zip)
c'est le fichier !

**Comment by jmontoyaa** [comment]
Oui, mais il faut l'exercice d'origin.

**Comment by alexiye** [comment]
Le fichier qti2_export_1.zip est le fichier original que j'ai essayé de télécharger. Je ne comprends pas votre demande.

**Comment by jmontoyaa** [comment]
Le fichier "qti2_export_1.zip" a été créé par chamilo?

**Comment by alexiye** [comment]
Il doit y avoir un lien avec cette erreur :
https://github.com/chamilo/chamilo-lms/issues/2276
essai sur le portail : Création d'un cours puis essai d'importation et affichage suivant :
Notice: Undefined property: stdClass::$save_correct_answers in /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php on line 1803

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'save_correct_answers' cannot be null in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(Array) #1 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/11.chamilo.org/www/main/inc/lib/database.lib.php(450): Doctrine\DBAL\Statement->execute(Array) #3 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(1824): Database::insert('c_quiz', Array) #4 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(188): Chamilo\CourseBundle\Component\CourseCopy\CourseRestorer->restore_quizzes(0, false, '') #5 /var/www/11.chamilo.org/www/main/coursecopy/import_backup.php(101): Chamilo\CourseBun in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 118

**Comment by alexiye** [comment]
Ce qui est curieux c'est que l'import qti2 ne fonctionne pas non plus sur chamilo 1.11.4
Par contre si j'importe un cours complet avec les exercices dans 1.11.4 cela fonctionne ( j'ai les parcours et les exercices) mais cela ne fonctionne pas dans la 1.11.6.alpha1.

**Comment by alexiye** [comment]
Je viens de me rendre compte que l'import qti2 ne fonctionne pas non plus dans la 1.9.10.2 avec un exercice créé dans 1.9.10.2 !
Au secours ! je vais tourner bourrique.
Bon ben je vais exporter mes cours vers la 1.11.4 et puis les exporter vers la 1.11.6...

**Comment by alexiye** [comment]
j'ai essayé l'export d'un exercice qti2 de chamilo 1.11.4 vers 1.11.6.alpha1 et cela ne fonctionne pas non plus !

**Comment by jmontoyaa** [comment]
Pour que je puisse tester il faudra:

1. Créer un exercise dans https://11.chamilo.org/ (admin/admin)
2. Créer l'export qti de l'exercice.
3. Créer un autre cours et faire l'import qti.

**Comment by alexiye** [comment]
ok let's go

**Comment by alexiye** [comment]
voilà c'est fait :https://11.chamilo.org/courses/JECREEUNEXERCICEPOURLEXPORTQTI2/index.php?id_session=0
https://11.chamilo.org/main/exercise/admin.php?cidReq=JECREEUNCOURSPOURLIMPORTDUNEXER&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=748

**Comment by alexiye** [comment]
C'est quoi un exercice avec des questions bien configurées ?
