### ISSUE TITLE
Importing course with learning path generates error on "created_on cannot be null"

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2784]
**Describe**
I'm trying to import a course generated in 1.11.8 in a 1.11.x portal (2019-01-21) and I get this error:
```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_on' cannot be null in /x/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117 
Stack trace: 
#0 /x/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(Array) 
#1 /x/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\DBAL\Driver\PDOStatement->execute(Array) 
#2 /x/web/htdocs/main/inc/lib/database.lib.php(475): Doctrine\DBAL\Statement->execute(Array) 
#3 /x/web/htdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(2734): Database::insert('c_lp', Array) 
#4 /x/web/htdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(198): Chamilo\CourseBundle\Component\CourseCopy\CourseRestorer->restore_learnpaths(0, false, in /x/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
```
I cannot share the contents of the course, but it contains a learning path, which for some reason does have "null" in the "created_on", "modified_on" and "publicated_on" columns.

**Expected behaviour**
The import script should "tolerate" NULL values and set a different default value of api_get_utc_datetime(), maybe...

**Comment by ywarnier** [comment]
I don't have the backup anymore nor a direct easy way to generate it, so I'll assume this is ok. The commit looks good and like it makes sense anyway.
