### ISSUE TITLE
Error when creating template from document, without giving image

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3184]
When trying to convert a document to a template without giving an image, an error is generated.

The form to convert the document to template should add a red asterisk near the image file input, and show a normal warning and return to the form if no image was provided.

Notice: Undefined variable: new_file_name in /var/www/chamilo111x/main/document/document.php on line 1539
1 | 0.0019 | 804272 | {main}(  ) | .../document.php:0

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity  constraint violation: 1048 Column 'image' cannot be null in  /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121 Stack trace: #0  /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(121):  PDOStatement->execute(Array) #1  /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153):  Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/chamilo111x/main/inc/lib/database.lib.php(460):  Doctrine\DBAL\Statement->execute(Array) #3 /var/www/chamilo111x/main/inc/lib/document.lib.php(1548):  Database::insert('templates', Array) #4 /var/www/chamilo111x/main/document/document.php(1539):  DocumentManager::set_document_as_template('top-template', '', 3713,  'SURVEYTEST', 1, NULL) #5 {main}  Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity  constraint violation: 1048 Column 'image' cannot be null in  /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php  on line 103
1 | 0.0019 | 804272 | {main}(  ) | .../document.php:0
2 | 0.4250 | 27152208 | DocumentManager::set_document_as_template(  ) | .../document.php:1539
3 | 0.4250 | 27152584 | Database::insert(  ) | .../document.lib.php:1548
4 | 0.4254 | 27198632 | Doctrine\DBAL\Statement->execute(  ) | .../database.lib.php:460

**Comment by ywarnier** [comment]
There is no message when we get back to the form, but at least the red asterisk is there, and that's enough for now. Closing. Thanks.
