### ISSUE TITLE
Zonas de imágen

### ISSUE THREAD

**Issue by martincasalis** [chamilo/chamilo-lms#3201]
Cuando creo un ejercicio en el cual incluyo una prueba de Zona de Imagen y luego lo incluyo en una lección, siempre da error al momento de generar el puntaje de ese ejercicio.

Pasos para reproducir el problema:
1. Generar un ejercicio que incluya una pregunta de Zona de Imagen.
2. Probar ese ejercicio, al finalizar lo evalúa correctamente y da por aprobado.
3. Incluir ese mismo ejercicio en una lección.
4. Volver a probar el ejercicio, pero ingresando desde la lección, en este caso evalúa incorrectamente el ejercicio en ese punto de Zona de Imagen.

**Comportamiento esperado**
Que evalúe correctamente el ejercicio, estando dentro o fuera de una lección.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
- Plataforma campus.chamilo.org
- Navegador chrome version 80.0.3987.163 (Build oficial) (64 bits)

**Contexto adicional**
Lo he probado en una instalación en Windows local, y me ocurre lo mismo.

**Comment by ywarnier** [comment]
@martincasalis lo vamos a revisar, pero el código de zonas de imágenes siendo particularmente complejo, es probable que una corrección no llegue hasta la siguiente versión mayor. Por mientras, sugerimos no usar esta combinación en particular

**Comment by christianbeeznest** [comment]
It is checked and improved with this commit https://github.com/chamilo/chamilo-lms/pull/7248/commits/1c7772f39bc10f60badd2bf4babcd8a68b50e2da

Thanks for confirmation.

**Comment by ywarnier** [comment]
When creating the question the first time, I get a blank page on /main/exercise/admin.php?cid=16&sid=0&gid=0&gradebook=0&origin=&newQuestion=yes&answerType=6&exerciseId=1 and I get this in the error_log:
```
PHP Fatal error:  Uncaught Error: Call to a member function selectTitle() on false in public/main/exercise/hotspot_admin.inc.php:19
Stack trace:
  #0 public/main/exercise/admin.php(638): require()
  #1 {main}
    thrown in public/main/exercise/hotspot_admin.inc.php on line 19
```

**Comment by ywarnier** [comment]
Otherwise this seems to work for me. I can see the test is complete, I can see my (100%) score and I can see the check mark in the left menu (although low contrast for now) confirming this step is done.

**Comment by ywarnier** [comment]
<img width="3738" height="1760" alt="Image" src="https://github.com/user-attachments/assets/727d8c62-ddaa-456f-825d-41310e58f440" />

**Comment by christianbeeznest** [comment]
> When creating the question the first time, I get a blank page on /main/exercise/admin.php?cid=16&sid=0&gid=0&gradebook=0&origin=&newQuestion=yes&answerType=6&exerciseId=1 and I get this in the error_log:
> 
> ```
> PHP Fatal error:  Uncaught Error: Call to a member function selectTitle() on false in public/main/exercise/hotspot_admin.inc.php:19
> Stack trace:
>   #0 public/main/exercise/admin.php(638): require()
>   #1 {main}
>     thrown in public/main/exercise/hotspot_admin.inc.php on line 19
> ```

It is fixed with this commit https://github.com/chamilo/chamilo-lms/pull/7271/commits/d1088d5ca0b3a597eaf15e85c8bc2c00ffb915bd

Thanks for confirmation.

**Comment by NicoDucou** [comment]
All good with the first creation of a hot spot question type.
