### ISSUE TITLE
Personal data page error

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3342]
Accessing https://11.chamilo.org/main/social/personal_data.php gives an error (tried with user admin/admin) :
```
Notice: Undefined index: course in /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php on line 1758

Warning: Invalid argument supplied for foreach() in /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php on line 1763

Notice: Undefined index: course in /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 183

Fatal error: Uncaught Error: Call to a member function setValue() on null in /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php:183
Stack trace:
#0 /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(553): Doctrine\ORM\PersistentCollection-&gt;hydrateAdd(Object(Chamilo\CourseBundle\Entity\CTool))
#1 /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(179): Doctrine\ORM\Internal\Hydration\ObjectHydrator-&gt;hydrateRowData(Array, Array, Array)
#2 /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(140): Doctrine\ORM\Internal\Hydration\ObjectHydrator-&gt;hydrateAllData()
#3 /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(997): Doctrine\ORM\Internal\Hydration\AbstractHydrator-&gt;hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement) in /furanet/sites/11.chamilo.org/web/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 183
```

With an older version of Chamilo I have alos this kind of error which should be corrected at the same time : 
```
[Mon Jun 29 17:12:41.989124 2020] [proxy_fcgi:error] [pid 85227] [client 192.168.11.9:6683] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Chamilo\\UserBundle\\Entity\\User::setLastLogin() must be an instance of DateTime, null given, called in /data/chamilo-lms-1.11.x-2020-04-23-7.3/src/Chamilo/UserBundle/Repository/UserRepository.php on line 1265 and defined in /data/chamilo-lms-1.11.x-2020-04-23-7.3/src/Chamilo/UserBundle/Entity/User.php:1454
Stack trace:
#0 /data/chamilo-lms-1.11.x-2020-04-23-7.3/src/Chamilo/UserBundle/Repository/UserRepository.php(1265): Chamilo\\UserBundle\\Entity\\User->setLastLogin(NULL)
#1 /data/chamilo-lms-1.11.x-2020-04-23-7.3/main/social/personal_data.php(200): Chamilo\\UserBundle\\Repository\\UserRepository->getPersonalDataToJson(9605, Array)
#2 {main}
  thrown in /data/chamilo-lms-1.11.x-2020-04-23-7.3/src/Chamilo/UserBundle/Entity/User.php on line 1454'
```

Tried with Chamilo 1.11.x updated today (2020-06-30) for the first error log.

**Comment by ywarnier** [comment]
The patch looks good but the same error still appear on https://11.chamilo.org/main/social/personal_data.php, even after a git pull, a composer install and a chash fct.

**Comment by ywarnier** [comment]
Still broken...
```
Notice: Undefined index: course in htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php on line 1758

Warning: Invalid argument supplied for foreach() in htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php on line 1763

Notice: Undefined index: course in htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 183

Fatal error: Uncaught Error: Call to a member function setValue() on null in htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php:183
Stack trace:
#0 htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(553): Doctrine\ORM\PersistentCollection->hydrateAdd(Object(Chamilo\CourseBundle\Entity\CTool)) 
#1 htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(179): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData(Array, Array, Array) 
#2 htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(140): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData() 
#3 htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(997): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement) in htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php on line 183
```

**Comment by ywarnier** [comment]
Yes, it looks like that fixed it! Thanks.
