### ISSUE TITLE
Fatal error(s) on installation

### ISSUE THREAD

**Issue by serhio-w03** [chamilo/chamilo-lms#3710]
**Describe**
Despite fulfilling/meeting all the requirements from the documentation and installation script controls regarding to PHP modules, the install procedure still generates  fatal errors: 

Fatal error: Call to undefined function filter_var()
Fatal error: Uncaught Error: Call to undefined function token_get_all() 

**Expected behavior**
after presence of modules is checked, process ends with no interruption

**Server
 - OS: detected on CentOS 8/php7.3, confirmed on FreeBSD 12.2, OpenBSD-67
 - Version of Chamilo:  1.11.14
 - Version of PHP: 7.3, 7.4

**Additional context**
modules php-tokenizer,  php-filter should be checked for presence before installing the scripts

/* full list of modules from one of (FreeBSD with php 7.4) my inst. script
php74-mysqli mod_php74 \
php74-pdo_mysql php74-gd php74-zlib  php74-session php74-zip \
php74-curl php74-xsl php74-openssl \
php74-json php74-iconv php74-mbstring php74-intl php74-fileinfo \
php74-ctype php-xapian php74-ldap \
php74-pecl-APCu php74-opcache \
**php74-tokenizer php74-filter** 
*/

**Comment by serhio-w03** [comment]
installation step 7:

Fatal error: Uncaught Error: Call to undefined function token_get_all() in /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php:54 Stack trace: #0 /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/PhpParser.php(60): Doctrine\Common\Annotations\TokenParser->__construct() #1 /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(380): Doctrine\Common\Annotations\PhpParser->parseUseStatements() #2 /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(301): Doctrine\Common\Annotations\AnnotationReader->collectParsingMetadata() #3 /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(142): Doctrine\Common\Annotations\AnnotationReader->getImports() #4 /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doct in /usr/local/www/apache24/five.vegova.si/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/TokenParser.php on line 54

hard to find missing php extensions :
php74-tokenizer php74-filter 👍 

Please, add those two to the (check) list of php extensions needed  (installation procedure step 2). Both are needed by doctrine:
