### ISSUE TITLE
Problema en actualización de 1.11.12 a 1.11.14

### ISSUE THREAD

**Issue by lopezsalexander** [chamilo/chamilo-lms#3736]
Al momento de actualizar Chamilo a la ultima versión, descargo el zip de Github, descomprimo y copio los archivos sobre la carpeta de Chamilo en producción, luego de esto la página web no carga y en los logs de Apache aparece el error: 

`[Mon Dec 28 15:03:46.764203 2020] [php7:error] [pid 1196] [client xxx.xxx.xxx.xxx:4100] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Gedmo\\Mapping\\MappedEventSubscriber::loadMetadataForObjectClass() must implement interface Doctrine\\Common\\Persistence\\ObjectManager, instance of Doctrine\\ORM\\EntityManager given, called in /var/www/chamilo/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php on line 46 and defined in /var/www/chamilo/vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php:196\nStack trace:\n#0 /var/www/chamilo/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php(46): Gedmo\\Mapping\\MappedEventSubscriber->loadMetadataForObjectClass()\n#1 /var/www/chamilo/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Gedmo\\AbstractTrackingListener->loadClassMetadata()\n#2 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(246): Doctrine\\Common\\EventManager->dispatchEvent()\n#3 /var/www/chamilo/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(306): Doctr in /var/www/chamilo/vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php on line 196`

### Resultado actual

Error en actualización, se debe realizar rollback a versión 1.11.12

### Resultado esperado

Actualización de Chamilo

### Pasos para reproducir

OS: Ubuntu Server 20.04
Apache/2.4.41
PHP 7.4.3
MariaDB Ver 15.1 Distrib 10.5.8

Actualizar directamente sobre entorno con Chamilo 1.11.12 sobreescribiendo a partir de la descarga del zip de Github.

### Version de Chamilo

1.11.12 a 1.11.14

**Comment by henrynicolas** [comment]
Hola amigo tengo el mismo problema llegaste a resolverlo?

**Comment by nosolored** [comment]
Hola.

Si descargas del Github de Chamilo debe generar el directorio vendor y web mediante composer

Lo aconsejable es descargar la versión de https://chamilo.org/es/descargar/ que ya contiene los directorios vendor y web

Saludos.

**Comment by tisujeck** [comment]
Problem still persists despite updating directly from chamilo.org. I would appreciate further discussion in english as there might be more international users out there experiencing the same problem.

**Comment by lantgonzalez** [comment]
> Hola.
> 
> Si descargas del Github de Chamilo debe generar el directorio vendor y web mediante composer
> 
> Lo aconsejable es descargar la versión de https://chamilo.org/es/descargar/ que ya contiene los directorios vendor y web
> 
> Saludos.

El mismo problema tengo yo y en mi caso sucede con el release oficial que se encuentra en la página de descargas. ¿Alguien ha logrado resolverlo?

**Comment by elyugos** [comment]
Hola tuve el mismo problema: 
Solución borrar la carpeta **vendor** y volver a copiarla.

**Comment by SebRevol** [comment]
Hi, I confirm it fixed my issue (cf #3765 )
Thanks!

**Comment by henrynicolas** [comment]
> Hola tuve el mismo problema:
> Solución borrar la carpeta **vendor** y volver a copiarla.

entiendo esto es borrar la carpeta vendor y volver al copiarla del paquete de instalación nuevo, o en todo caso copiar la carpeta antigua de la version anterior ?
