### ISSUE TITLE
PHP Error on Update to 1.11.14

### ISSUE THREAD

**Issue by Craftoncu** [chamilo/chamilo-lms#3760]
**Describe**
Type Error after update from 1.11.11 to 1.11.14.
Unzipped new files over old.

 - OS: Linux Deb. Buster 10 64x

Stacktrace:
` PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Gedmo\\Mapping\\MappedEventSubscriber::loadMetadataForObjectClass() must implement interface Doctrine\\Common\\Persistence\\ObjectManager, instance of Doctrine\\ORM\\EntityManager given, called in /var/www/campush.de/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php on line 46 and defined in /var/www/campush.de/vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php:196\nStack trace:\n#0 /var/www/campush.de/vendor/gedmo/doctrine-extensions/lib/Gedmo/AbstractTrackingListener.php(46): Gedmo\\Mapping\\MappedEventSubscriber->loadMetadataForObjectClass(Object(Doctrine\\ORM\\EntityManager), Object(Doctrine\\ORM\\Mapping\\ClassMetadata))\n#1 /var/www/campush.de/vendor/doctrine/common/lib/Doctrine/Common/EventManager.php(59): Gedmo\\AbstractTrackingListener->loadClassMetadata(Object(Doctrine\\ORM\\Event\\LoadClassMetadataEventArgs))\n#2 /var/www/campush.de/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(246): Doctrine\\Common\\EventMana in /var/www/campush.de/vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/MappedEventSubscriber.php on line 196
`

**Comment by mk111** [comment]
same as #3736
did you empty caches ? and restarted web services?

**Comment by lonesomewalker** [comment]
Since i know whom you are working for...

For future "issues" please check this first:
https://11.chamilo.org/documentation/installation_guide.html#3._Upgrade

**Comment by Coursenligne** [comment]
It looks like the info given in the case is not accurate.
This sounds like the case here is the one described on the forum : https://forum.chamilo.org/viewtopic.php?f=52&t=11539
The user claims having trouble from Version 1.11.6 to 1.11.14.
I was suspecting a PHP issue as, if my memory is good, 1.11.6 allowed PHP5, which is not working with 1.11.14.

**Comment by mk111** [comment]
I'm sorry,
 I started from the fact that v11.14 on php 7.1+ de-facto works from clean installation:
the upgrade process for minor versions is very straigtforward: overwrite existing files ... it overwrites all application scripts including the necessary libraries (symfony, doctrine, twig, zend,...). All the caches need to be cleaned too. On the system where the distribution was made, all dependencies between php / libraries were resolved. On the target system, however, this is not necessary. Note that the upgrade does not start any of the package managers/Composer to resolve any additional dependencies and whether the requirements for additional php modules and / or their versions are otherwise checked.

**Comment by Coursenligne** [comment]
I agree with You, but, as 1.11.6 was PHP 5 compliant, if the customer did install this version, it becomes impossible to upgrade 1.11.14 as only PHP7+ compliant.
The PHP message let me think of this kind of mistake.

**Comment by lonesomewalker** [comment]
Sorry to bother both of you, but as you can read initially:

Type Error after update from 1.11.11 to 1.11.14

This is related to not correctly prepare for upgrade.

**Comment by mk111** [comment]
i do not like this part of the error message :  "Doctrine\\Common\\Persistence\\ObjectManager," . on my system Persistence is not part of the  Common  ... so i must agree with @lonesomewalker ; ... 
<img width="583" alt="abc02" src="https://user-images.githubusercontent.com/4478116/106036623-df902b00-60d5-11eb-930f-2be0a8484343.png">

**Comment by mk111** [comment]
i must agree with @lonesomewalker ;
this part of the error i do not like : `Doctrine\\Common\\Persistence\\ObjectManager`
Persistence is not part of the Common any more and should be located in vendor\doctrine\persistence ...

**Comment by SebRevol** [comment]
Hi all, I have the same issue after an update from 1.11.12 to 1.11.14. 
I followed the procedure described in [https://11.chamilo.org/documentation/installation_guide.html#3._Upgrade](https://11.chamilo.org/documentation/installation_guide.html#3._Upgrade) which succesfully worked for my previous 1.11.10 to 1.11.12 update.

I'm very unexperimented in php, but I noticed that chamilo 1.11.14 archive contains both vendor/doctrine/persistence/**lib**/Doctrine/Persistence/ and vendor/doctrine/persistence/**lib**/Doctrine/**Common**/Persistence folders  with quite similar php files in them (but that's also the case in 1.1.12 archive).

**Comment by SebRevol** [comment]
As suggested in #3736, deleting and replacing vendor directory fixed the issue.
