### ISSUE TITLE
Le lien données personnel renvoitune erreur HTTP 500

### ISSUE THREAD

**Issue by yverhenne** [chamilo/chamilo-lms#4666]
Depuis mon passage en 1.11.18, le lien données personnelles ne fonctionne plus. Lorsque je clic dessus, il me met une page HTTP error 500. Ce qui pose problème pour le RGPD.
Est aussi le cas chez vous?
Si ça peut aider voici le log d'erreur

[31-Mar-2023 11:09:19 UTC] PHP Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.signature' in 'field list' in .../public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 .../public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 .../public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1304): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 .../public_html/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(897): Doctrine\DBAL\Connection->executeQuery('SELECT t0.iid A...', Array, Array)
#3 .../public_html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(178): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, NULL, NULL, NULL)
#4.../public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 79

Ma configuration:
[SERVER] | $_SERVER["HTTP_USER_AGENT"] | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54 

  [SERVER] | $_SERVER["SERVER_PROTOCOL"] | HTTP/1.1 | 
  [SERVER] | php_uname() | Linux fr-int-web936.main-hosting.eu  #1 SMP Tue Nov 22 22:59:23 EST 2022 x86_64

[SERVER]	[$_SERVER["HTTP_USER_AGENT"]	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.5
[SERVER]	[$_SERVER["SERVER_PROTOCOL"]](http://be.php.net/reserved.variables.server)	HTTP/1.1	
[SERVER]	[php_uname()](http://be2.php.net/php_uname)	Linux fr-int-web936.main-hosting.eu 4.18.0-425.3.1.lve.el8.x86_64 #1 SMP Tue Nov 22 22:59:23 EST 2022 x86_64

**Comment by yverhenne** [comment]
Après plusieurs heures j'ai enfin trouvé.
La mise à jour vers la version 1.11.18 ne fait pas les modifications sur 2 tables:
ALTER TABLE c_attendance_sheet ADD signature longtext NULL;
ALTER TABLE c_attendance_calendar ADD blocked tinyint(1) NULL;
Il faut donc faire la requête manuellement via PHP My admin.

J'ai trouvé la solution grace à cet article de Beeznet sur la signature des feuilles d'émargement en ligne:
[https://beeznest.com/fr/2023/03/20/la-s ... ns-chamilo](https://beeznest.com/fr/2023/03/20/la-signature-des-feuilles-demargement-en-ligne-directement-dans-chamilo)

J'en ai donc profité pour installer la fonction.

Merci à eux
