### ISSUE TITLE
Import exercises Qti2: Responding 500 error

### ISSUE THREAD

**Issue by ashishkpaul** [chamilo/chamilo-lms#4812]
**To Reproduce**
1. Go to 'Test'
2. Click on 'Import exercises Qti2'
3. Upload qti2.zip file
```POST
https://lms.dingpack.com/main/exercise/qti2.php?cidReq=2NDCOURSE&id_session=0&gidReq=0&gradebook=0&origin=
[HTTP/2 500 Internal Server Error 74ms]

	
POST
	https://lms.dingpack.com/main/exercise/qti2.php?cidReq=2NDCOURSE&id_session=0&gidReq=0&gradebook=0&origin=
Status
500
Internal Server Error
VersionHTTP/2
Transferred4.07 kB (0 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest

Use of navigator.sendBeacon instead of synchronous XMLHttpRequest during unload and pagehide improves user experience. jquery.min.js:4:15143
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. qti2.php
Error: An unexpected error occurred spoofer.js:1:38935
```
and the console output is

```
2023/07/16 14:35:19 [error] 3536688#3536688: *931 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught LogicException: To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead. in /var/www/html/dingpack/dingpack-1.11.20/vendor/symfony/dom-crawler/Crawler.php:1296
Stack trace:
#0 /var/www/html/dingpack/dingpack-1.11.20/vendor/symfony/dom-crawler/Crawler.php(791): Symfony\Component\DomCrawler\Crawler->createCssSelectorConverter()
#1 /var/www/html/dingpack/dingpack-1.11.20/main/exercise/export/exercise_import.inc.php(354): Symfony\Component\DomCrawler\Crawler->filter()
#2 /var/www/html/dingpack/dingpack-1.11.20/main/exercise/export/exercise_import.inc.php(337): parseQti2()
#3 /var/www/html/dingpack/dingpack-1.11.20/main/exercise/export/exercise_import.inc.php(129): qti_parse_file()
#4 /var/www/html/dingpack/dingpack-1.11.20/main/exercise/qti2.php(76): import_exercise()
#5 /var/www/html/dingpack/dingpack-1.11.20/main/exercise/qti2.php(87): importFile()
#6 {main}
  thrown in /var/www/html/dingpack/dingpack-1.11.20/vend" while reading response header from upstream, client: 140.238.255.121, server: lms.dingpack, request: "POST /main/exercise/qti2.php?cidReq=2NDCOURSE&id_session=0&gidReq=0&gradebook=0&origin= HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "lms.dingpack", referrer: "https://lms.dingpack/main/exercise/qti2.php?cidReq=2NDCOURSE&id_session=0&gidReq=0&gradebook=0&origin="
```

**Server
 - OS: [Linux Ubuntu 22.04]
 - Version of Chamilo:  [1.11.20]
 - Version of PHP: [7.4]

**Comment by ywarnier** [comment]
Just tested without issue. It looks like you have some missing library or PHP extension. Could you post the result of the following command here ?
`php7.4 -m`

I have the following, but it's a developer setup, so a bit more than what is required.
```
[PHP Modules]
apcu
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tideways_xhprof
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```
In particular, I'm interested in what you have that look like 'xml' or 'xsl' (libxml, SimpleXML, xml, xmlreader, xmlrpc, xmlwriter, xsl), with a particular suspicion on xsl and xml missing from your system...

The QTI format is basically XML, so if you try to import new users through the XML format in the administration section, chances are you will have the same issue (if my suspicion is correct).

**Comment by ashishkpaul** [comment]
Thanks for your time sir, few days ago, i tried chamilo lms on localhost and resolve the issue by running the commands: 
```
sudo apt install php7.4 php7.4-fpm php7.4-mysql php-common php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-readline php7.4-mbstring php7.4-xml php7.4-gd php7.4-curl php-imagick php7.4-zip php7.4-xml php7.4-bz2 php7.4-intl php7.4-bcmath php7.4-gmp
```

and after that
```
composer require symfony/css-selector
```

**Comment by ywarnier** [comment]
OK, thanks for the details. The composer require should not have been necessary, though.
