### ISSUE TITLE
plugin: before_login not working.

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#5138]
**Describe**
Pl;ugin: before_login

Is currently not working.

**To Reproduce**
Install plugin configure options.
no region assigned nothing shows. 
Region assigned it trows error:
`[05-Feb-2024 21:38:09 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Call to a member function setCustomElementTemplate() on null in /home/dhtonl/public_html/plugin/before_login/index.php:37
Stack trace:
#0 /home/dhtonl/public_html/main/inc/lib/plugin.lib.php(507): require()
#1 /home/dhtonl/public_html/main/inc/lib/plugin.lib.php(412): AppPlugin->get_all_plugin_contents_by_region('login_top', Object(Template), false)
#2 /home/dhtonl/public_html/main/inc/lib/template.lib.php(970): AppPlugin->load_region('login_top', Object(Template), false)
#3 /home/dhtonl/public_html/main/inc/lib/template.lib.php(260): Template->set_plugin_region('login_top')
#4 /home/dhtonl/public_html/main/inc/lib/userportal.lib.php(28): Template->__construct(NULL)
#5 /home/dhtonl/public_html/index.php(31): IndexManager->__construct(NULL)
#6 {main}
  thrown in /home/dhtonl/public_html/plugin/before_login/index.php on line 37`

**Comment by ywarnier** [comment]
Fixed and ready for inclusion in 1.11.30
