### ISSUE TITLE
Sec token error in forums show an error when adding or editing content in categories

### ISSUE THREAD

**Issue by Kaneda-1** [chamilo/chamilo-lms#5417]
Tue Apr 23 02:27:36.068349 2024] [php7:error] [pid 2844933] [client xxx.xx.xx.xxx:57432] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Security::filter_terms() must be of the type string, null given, called in /.../main/inc/lib/security.lib.php on line 319 and defined in /.../main/inc/lib/security.lib.php:463\nStack trace:\n#0 /.../main/inc/lib/security.lib.php(319): Security::filter_terms(NULL)\n#1 /.../main/forum/forumfunction.inc.php(5077): Security::remove_XSS(NULL, 5, true)\n#2 /.../main/forum/forumfunction.inc.php(439): prepare4display(NULL)\n#3 /.../main/forum/forumfunction.inc.php(125): show_add_forum_form(Array, 0)\n#4 /.../main/forum/index.php(101): handle_forum_and_forumcategories(0)\n#5 {main}\n  thrown in /.../main/inc/lib/security.lib.php on line 463, referer: https://domain.com/main/forum/index.php?cidReq=IDCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=add&content=forum&lp_id=

[Tue Apr 23 02:30:23.167473 2024] [php7:error] [pid 2846641] [client xxx.xx.xx.xxx:57550] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Security::filter_terms() must be of the type string, null given, called in /.../main/inc/lib/security.lib.php on line 319 and defined in /.../main/inc/lib/security.lib.php:463\nStack trace:\n#0 /.../main/inc/lib/security.lib.php(319): Security::filter_terms(NULL)\n#1 /.../main/forum/forumfunction.inc.php(5077): Security::remove_XSS(NULL, 5, true)\n#2 /.../main/forum/forumfunction.inc.php(439): prepare4display(NULL)\n#3 /.../main/forum/forumfunction.inc.php(125): show_add_forum_form(Array, 0)\n#4 /.../main/forum/index.php(101): handle_forum_and_forumcategories(0)\n#5 {main}\n  thrown in /.../main/inc/lib/security.lib.php on line 463, referer: https://domain.com/main/forum/index.php?cidReq=IDCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=edit&content=forum&id=110553

**Comment by ywarnier** [comment]
Fixed in 03e1960b (before 1.11.28)
