### ISSUE TITLE
Forum doesn't get created (some security filtering)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5550]
On https://campus.chamilo.org (1.11.26+), there is an issue with the creation of forum *in some courses* (not all). The forum category gets created no problem, but when creating a forum with a simple title (even just 3 letters together with no special char), I get:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Security::filter_terms() must be of the type string, null given, called in main/inc/lib/security.lib.php on line 325 and defined in /main/inc/lib/security.lib.php:469
Stack trace:
#0 /main/inc/lib/security.lib.php(325): Security::filter_terms(NULL)
#1 /main/forum/forumfunction.inc.php(5077): Security::remove_XSS(NULL, 5, true)
#2 /main/forum/forumfunction.inc.php(439): prepare4display(NULL)
#3 /main/forum/forumfunction.inc.php(125): show_add_forum_form(Array, 0)
#4 /main/forum/index.php(101): handle_forum_and_forumcategories(0)
#5 {main}
  thrown in /main/inc/lib/security.lib.php on line 469
```

**Comment by NicoDucou** [comment]
Already fixed in 1.11.x with this commit : 03e1960b1d83e4df59f1203cdfaa7380d9104ba4
