### ISSUE TITLE
Unable to upload SCORM File 

### ISSUE THREAD

**Issue by etree2024** [chamilo/chamilo-lms#5645]
**Describe**

I am uploading SCORM file in 1.11.26 made in iSpring these SCORM packages have been tested in 1.22.24 and work fine on the same server. 

Errors found in browser 
**1st error** 
[The requested URL was not found on this server.](index.php:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received)
**2nd Error** 
index.php:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at xhr.onreadystatechange (bigUpload.js:191:26)
**3rd  Error** 
/main/inc/lib/javascript/bigupload/inc/bigUpload.php?cidReq=EXAMS&id_session=0&gidReq=0&gradebook=0&origin=&action=upload&key=ALC-Bk1-L4.zip&origin=learnpath:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET

**To Reproduce**
1. Go to Learning Path
2. Click on upload SCORM Package 
3. select SCORM Package
4. Upload SCORM Package 
5. File stops at 13 to 14 percent 
6. Never finishes upload of for SCORM Package

**Expected behavior**
I am expecting to see completion of upload of SCORM and be able to navigate to it. 

**Screenshots**

<img width="1620" alt="Screenshot 2024-07-08 at 13 55 08" src="https://github.com/chamilo/chamilo-lms/assets/161403104/f2434c0a-7167-4dfa-aec8-0d9c496a4a71">

**Desktop (please complete the following information):**
 - OS: MAC OS X and Windows 11
 - Browser Chrome and Safari

**Server
 - OS: Windows Server as well as MAX OS X with MAMP
 - Version of Chamilo:  Your version is up-to-date: Chamilo 1.11.26
 - Version of PHP: 7.4.27

**Additional context**
Add any other context about the proble
[PHP_Settings.pdf](https://github.com/user-attachments/files/16126695/PHP_Settings.pdf)
m here.

**Comment by etree2024** [comment]
I have also found issues with the documents upload function when using the drag and drop method. If I switch it to I have to select a file and upload it works fine.

**Comment by etree2024** [comment]
I have fixed the issues with uploading files in documents with settings and set the upload files to 0777 instead of the default 0666 that was set by default

**Comment by etree2024** [comment]
also getting this JSON issue from the file in Chrome 

Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at xhr.onreadystatechange (bigUpload.js:191:26)

**Comment by ywarnier** [comment]
Due to this `bigUpload.php Line 191 EOF error`, I'm wondering if some of your files have not been damaged during upload of Chamilo or something like that.

We would need a minimal version of your SCORM package to try it out, sadly.
