### ISSUE TITLE
IMPORTAR EJERCICIOS Qti2_ HTTP ERROR 500

### ISSUE THREAD

**Issue by Xami267** [chamilo/chamilo-lms#5661]
Hola al momento de importar ejercicios Qti2 me muestra el siguiente mensaje:

![Screenshot_30](https://github.com/user-attachments/assets/b17fe105-3b11-4caa-83c1-08f61c62fd3f)

El archivo lo estoy descargando de una página creada también en chamilo. Por favor su ayuda.

La versión de chamilo que tengo es Chamilo 1.11.26

**Comment by NicoDucou** [comment]
Funciona bien en Chamilo 1.11.x con el archivo adjunto.

[qti2_export_388.zip](https://github.com/user-attachments/files/24372354/qti2_export_388.zip)

En Chamilo2 hay un problema con el archivo que no se importa correctamente en el servidor y entonces no se encuentra en archivo para unzipearlo. En los logs se puede ver el error siguiente : 

`[Mon Dec 29 19:36:20.039986 2025] [proxy_fcgi:error] [pid 1202103] [client 2800:200:e720:531:5146:8ec5:c027:94a:49588] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PhpZip\\Exception\\ZipException: File qti2_export_388.zip does not exist. in /var/www/testing24.beeznest.com/www/vendor/nelexa/zip/src/ZipFile.php:101\nStack trace:\n#0 /var/www/testing24.beeznest.com/www/public/main/exercise/export/exercise_import.inc.php(39): PhpZip\\ZipFile->openFile()\n#1 /var/www/testing24.beeznest.com/www/public/main/exercise/qti2.php(78): import_exercise()\n#2 /var/www/testing24.beeznest.com/www/public/main/exercise/qti2.php(89): importFile()\n#3 {main}\n  thrown in /var/www/testing24.beeznest.com/www/vendor/nelexa/zip/src/ZipFile.php on line 101', referer: https://testing24.beeznest.com/main/exercise/qti2.php?cid=17&sid=0&gid=0&gradebook=0&origin=`

**Comment by ywarnier** [comment]
This now works in virtue of this change 50a86b5c35cc94a6631f8e47cbfdda118c0d309d, which is related to #3277
