### ISSUE TITLE
Cannot generate PDF Certifcate

### ISSUE THREAD

**Issue by Arricdev** [chamilo/chamilo-lms#5910]
**Describe**

After migrating to 1.11.28
When I try to download a certificate in PDF i Get an error 500

generating html certificate is OK

Was working in 1.11.26

**To Reproduce**
1. Go to 'https://yourwebsite/certificates/index.php?id=XXX&user_id=XXX&action=export
2. See error

logs 

Wed Nov 06 11:51:30.968799 2024] [proxy_fcgi:error] [pid 3934032] [client 127.0.0.1:52186] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught LogicException: To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead. in  path-to-chamilo/vendor/symfony/dom-crawler/Crawler.php:1296\nStack trace:\n#0  path-to-chamilo/vendor/symfony/dom-crawler/Crawler.php(791): Symfony\\Component\\DomCrawler\\Crawler->createCssSelectorConverter()\n#1 path-to-chamilo/main/inc/lib/pdf.lib.php(345): Symfony\\Component\\DomCrawler\\Crawler->filter()\n#2  path-to-chamilo/certificates/index.php(84): PDF->html_to_pdf()\n#3 {main}\n  thrown in  path-to-chamilo/vendor/symfony/dom-crawler/Crawler.php on line 1296', referer: https://yourwebsite/certificates/index.php?id=xxx&user_id=xxxxx&action=export

**Expected behavior**

PDF Download

**Comment by Kaneda-1** [comment]
Similar a https://github.com/chamilo/chamilo-lms/issues/3774
download the /vendor folder from the url https://github.com/chamilo/chamilo-lms/releases/download/v1.11.28/chamilo-1.11.28.zip
and replaces the contents of the /vendor folder locally

The error you're seeing indicates that the CssSelector component from Symfony is missing, which is necessary for filtering with a CSS selector. Here's how to fix it:

Install the CssSelector component: Open a terminal in your project directory and run the following command to install the component
rm composer.lock
rm -rf web/ vendor/
composer clear-cache
composer update

**Comment by Arricdev** [comment]
Thanks for your answer, 

I already got the vendor/ dir when I migrated but the component seems to be missing.

Does that work if I install the component with composer on a QA server and then copy  vendor/ dir ? This would generate less downtime

**Comment by Arricdev** [comment]
Ok, it worked , thank you.
Maybe it would be great to update the release ?

**Comment by ywarnier** [comment]
Yes, we are working on a new release for within a few days.

**Comment by ywarnier** [comment]
Sorry for the long delay. Really working on closing all these issues now.
I cannot reproduce the issue, so I'm assuming it was either some local configuration or the issue has already been fixed through some other bug report. Closing.

**Comment by Arricdev** [comment]
Hi, This issue is not resolved with 1.11.32 , css-selector is still not in the vendor folder of the release, need to do composer update to have it.

$ pwd
/xxxxx/chamilo-1.11.32/vendor/symfony
$ ls
asset				framework-bundle		routing
cache				http-foundation			security
cache-contracts			http-kernel			security-acl
class-loader			intl				security-bundle
config				options-resolver		serializer
console				polyfill-ctype			service-contracts
debug				polyfill-iconv			stopwatch
dependency-injection		polyfill-intl-icu		templating
doctrine-bridge			polyfill-intl-idn		translation
dom-crawler			polyfill-intl-normalizer	twig-bridge
event-dispatcher		polyfill-mbstring		twig-bundle
expression-language		polyfill-php80			validator
filesystem			polyfill-util			var-exporter
finder				process				yaml
form				property-access

**Comment by ywarnier** [comment]
Re-opening on request by @Arricdev in #6424

**Comment by NicoDucou** [comment]
This issue was reported again on 20/10/2025
So to be revised for release 1.11.34

**Comment by Coursenligne** [comment]
I confirm the issue is still here 1.11.32.
I had to freshly reinstall Chamilo and can't get the PDF working to get the certificate. Other PDF are working fine so far.
The message is saying that css-selector is missing.

I don't know if it is related, but impossible to print certificate Landscape mode (a part of the certificate is printed on one page, and the other part on a second page).
Printing portrait mode is just OK.

**Comment by FernandoHiagon** [comment]
I confirm here too ! same version, fresh install version 1.11.32

**Comment by ywarnier** [comment]
I still cannot reproduce this in a local environement.

**Comment by ywarnier** [comment]
Could someone still experiencing the issue give me a more recent log from the error log to try and see what's wrong?

**Comment by ywarnier** [comment]
I see that, in my setup, css-selector is present in `vendor/symfony/css-selector`.
I also get it on a french install from source where there was nothing present before, so I assume this is related to a very specific server context, but it's really unclear how to get the issue. Maybe trying to run composer update from a PHP8 CLI? (instead of PHP7.4)
I assume this would have vastly more devastating effects, though.

**Comment by Coursenligne** [comment]
The actual issue is that you can't print Landscape correctly when viewing by Web.
Then, when you try to download the certificate, you get Error 500 this page is not working, impossible to treat the demand
Windows / WAMP server Php 7.4.33 // MySQL 5.7.44
Fresh Chamilo Install without any weird replacement of any directory.
I don't have css-selector directory in my install. It is not present in the zip file from Chamilo.org
Downloading PDF for other parts are just working fine

<img width="582" height="376" alt="Image" src="https://github.com/user-attachments/assets/ec6a4a86-9be4-457b-bf7f-d11fe73ed2e1" />

**Comment by Coursenligne** [comment]
And here are the logs (as it is a test server, I don't mind giving all the info :)
[01-Mar-2026 08:37:10 UTC] PHP Fatal error:  Uncaught LogicException: To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead. in C:\wamp64\www\chamilo1\vendor\symfony\dom-crawler\Crawler.php:1296
Stack trace:
#0 C:\wamp64\www\chamilo1\vendor\symfony\dom-crawler\Crawler.php(791): Symfony\Component\DomCrawler\Crawler->createCssSelectorConverter()
#1 C:\wamp64\www\chamilo1\main\inc\lib\pdf.lib.php(345): Symfony\Component\DomCrawler\Crawler->filter('link[rel="style...')
#2 C:\wamp64\www\chamilo1\certificates\index.php(84): PDF->html_to_pdf(Array, 'Certificat-a', NULL, false, false)
#3 {main}
  thrown in C:\wamp64\www\chamilo1\vendor\symfony\dom-crawler\Crawler.php on line 1296


If you want me to do something, please make sure to give a kind of step-by-step process, so I'm sure not to do a bad thing.

**Comment by Coursenligne** [comment]
Tested 1.11.38 (upgrade from 1.11.36) and still no images in PDF, but the certificate can be geerated.
This time there is no log at all.
PDF is generated without image.
Important notice, I didn't create any certificate this time, just using the default one.
I now have to take a bit of time to install 1.11.38 freshly and give a try and do the same with a certificate I create myself.

**Comment by ywarnier** [comment]
I'm moving this to 1.11.42 milestone. We had to publish a security update release so we did that through 1.11.40 and couldn't close this issue here in time for that.
